export const qk = {
  profile: (userId: string) => ["profile", userId] as const,
  board: (filters: unknown) => ["board", filters] as const,
  order: (id: string) => ["order", id] as const,
  record: (id: string) => ["record", id] as const,
  lines: (id: string) => ["lines", id] as const,
  payments: (id: string) => ["payments", id] as const,
  dispatches: (id: string) => ["dispatches", id] as const,
  activity: (id: string) => ["activity", id] as const,
  comments: (id: string) => ["comments", id] as const,
  siteDetails: (id: string) => ["site-details", id] as const,
  syncHealth: ["sync-health"] as const,
  salesSlim: (from: string | null) => ["analytics", "sales", from] as const,
  paymentsSlim: (from: string | null) => ["analytics", "payments", from] as const,
  deliveryPerformance: (from: string | null) => ["analytics", "delivery", from] as const,
  dispatchDaily: (from: string | null) => ["analytics", "dispatch-daily", from] as const,
  stageSnapshot: ["analytics", "stage-snapshot"] as const,
};
